version: '2.1'

services:
  cf-bot-discord:
    image: cf-bot-discord
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8081:8081
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 dist/index.js